repos:
  # pre-commit 기본 훅 모음
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # 파일 끝의 불필요한 공백 제거
      - id: trailing-whitespace
      # 파일 끝에 빈 줄 추가
      - id: end-of-file-fixer

  # flake8: Python 코드 린터
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  # autopep8: Python 코드 스타일 자동 정리
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        args: ["--max-line-length=80"] # 최대 줄 길이 설정

  # isort: import 문 정렬
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # mypy: Python 타입 검사 도구
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy
