[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "haerae-evaluation-toolkit"
version = "0.1.0"
authors = [
  { name = "Hanwool Lee", email = "gksdnf424@gmail.com" }
]
description = "A comprehensive, standardized validation toolkit for Korean Large Language Models (LLMs)."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
keywords = ["llm", "evaluation", "korean", "nlp", "benchmark", "hret"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Text Processing :: Linguistic",
]

[project.urls]
Homepage = "https://github.com/HAE-RAE/haerae-evaluation-toolkit"
Issues = "https://github.com/HAE-RAE/haerae-evaluation-toolkit/issues"

dependencies = [
    "transformers", 
    "torch>=2.0.0",        
    "openai>=1.0.0",       
    "datasets>=3.2.0",     
    "litellm>=1.59.0",     
    "math-verify",        
    "pandas",              
    "tqdm",
    "langdetect",
    "httpx",
    "vllm",
    "accelerate",
    "spacy",
    "scikit-learn"
]

[project.optional-dependencies]
dev = [
    "pre-commit==4.0.1",
    "pytest>=7.3.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["llm_eval*"]
