name: Check Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    # 3.10, 3.12에서 테스트 진행
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv pip install --system -e ".[dev]"

      - name: Run dataset tests
        run: |
          pytest llm_eval/test/test_datasets.py --cache-clear

      - name: Run evaluation tests
        run: |
          pytest llm_eval/test/test_evaluations.py

      - name: Run scaling tests
        run: |
          pytest llm_eval/test/test_scaling.py
